language: ruby
install:
  gem uninstall bundler
  gem install bundler --version '1.7.4'
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
script:
  - bundle exec rake spec:no_auth
